name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint & Test (Bun + Vitest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache dependencies (bun cache + node_modules)
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            client/node_modules
            server/node_modules
            shared/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Show tool versions
        run: |
          bun --version
          bunx vitest --version

      - name: Lint
        run: bun run lint

      - name: Test with coverage
        env:
          CI: true
        run: bun run test
